name: toplive
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  agora_rtc_engine: ^5.0.1
  alt_sms_autofill: ^1.0.0
  animate_do: ^2.1.0
  animations: null
  cached_network_image: ^3.2.0
  carousel_slider: ^4.0.0
  chat_bubbles: ^1.2.0
  cloud_firestore: ^3.1.11
  cupertino_icons: ^1.0.4
  dio: ^4.0.6
  dio_cache_interceptor: any
  dio_logger: ^4.0.8+8
  dropdown_button2: ^1.4.0
  ease: ^0.0.10
  firebase_auth: ^3.3.13
  firebase_core: ^1.14.0
  firebase_storage: ^10.2.13
  flutter_facebook_auth: ^4.2.0
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.1.5
  get: 4.6.1
  get_storage: ^2.0.3
  glass_kit: ^2.0.1
  google_sign_in: ^5.2.4
  image_downloader: ^0.31.0
  image_picker: ^0.8.5
  intl: ^0.17.0
  intl_phone_field: ^3.1.0
  permission_handler: ^9.2.0
  persistent_bottom_nav_bar: ^4.0.2
  pin_code_fields: ^7.4.0
  responsive_framework: ^0.1.7
  sentry_flutter: ^6.4.0
  tab_indicator_styler: ^2.0.0

flutter_assets:
  assets_path: assets/
  output_path: lib/core/resourses/
  filename: assets.dart
flutter_icons:
  android: launcher_icon
  ios: true
  remove_alpha_ios: true
  image_path: assets/images/logo.png
  flutter: null
dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  lints: 1.0.1
flutter:
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
